### PR TITLE
bumped pattern library version - Newsletter Signup | Legal messaging …

### PR DESCRIPTION
**Pull request by kimlarocca**
- [x] release the PR in nypr-design-system: https://github.com/nypublicradio/nypr-design-system/pull/53

- [x] update the dependency before merge

https://jira.wnyc.org/browse/DS-589
https://jira.wnyc.org/browse/DS-590

### CODE REVIEW

**Comment by walsh9** [comment]
It looks like the linked PR is closed. Can you open a new PR in nypr-design-system against the legacy branch?

**Comment by kimlarocca** [comment]
@walsh9 it's the same ticket as before, but I'll also add in the second related ticket

**Comment by walsh9** [comment]
sorry i meant the new PR

**Comment by kimlarocca** [comment]
ok done! thanks :)

**Pull request merged**
